version: '3'
services:
  db:
    env_file:
      - .env
    container_name: board-db
    image: mariadb
    ports:
      - "3306:3306"

  web:
    container_name: board-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/venv
      - .:/app/
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    command: sh ./start.sh
    stdin_open: true